argo-cd:
  nameOverride: argocd
  configs:
    params:
      server.insecure: true
  exec.enabled: true
  cm:
    accounts.admin: login
    accounts.admin.enabled: "true"
    accounts.acarter: login
    accounts.acarter.enabled: "true"
